FROM php:7.0-fpm-alpine
MAINTAINER Dave Nuñez <dnunez24@gmail.com>

ARG MAGE_VERSION
ARG MAGE_EDITION
ARG MAGE_REPO
ENV COMPOSER_HOME /.composer

# Install dependencies
RUN apk add --no-cache --virtual .build-deps \
    curl \
    freetype-dev \
    icu-dev \
    libjpeg-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    libxml2-dev \
    libxslt-dev \
    openssl-dev \
  && NPROC=$(getconf _NPROCESSORS_ONLN) \
  && docker-php-ext-install -j$NPROC \
    bcmath \
    ctype \
    curl \
    dom \
    iconv \
    intl \
    json \
    mbstring \
    mcrypt \
    opcache \
    pdo_mysql \
    soap \
    xml \
    xsl \
    zip \
  && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$NPROC gd \
  && curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer \
  && apk add --no-cache \
    freetype \
    icu \
    libjpeg-turbo \
    libmcrypt \
    libpng \
    libxslt \
  && apk del .build-deps

WORKDIR /tmp/magento

# Requires an auth.json file with Composer credentials for Magento repo
COPY auth.json /.composer/auth.json
RUN composer create-project \
    --no-interaction \
    --prefer-dist \
    --repository="${MAGE_REPO}" \
    magento/project-${MAGE_EDITION}-edition:${MAGE_VERSION} .

CMD tar -czf - -C /tmp/magento .
