FROM php:7.0-fpm-alpine
MAINTAINER Dave Nuñez <dnunez24@gmail.com>

ARG MAGE_EDITION
ENV MAGE_ROOT /var/www/html

# Install dependencies
RUN apk add --no-cache --virtual .build-deps \
    curl \
    freetype-dev \
    icu-dev \
    libjpeg-turbo-dev \
    libmcrypt-dev \
    libpng-dev \
    libxml2-dev \
    libxslt-dev \
    openssl-dev \
  && NPROC=$(getconf _NPROCESSORS_ONLN) \
  && docker-php-ext-install -j$NPROC \
    bcmath \
    ctype \
    curl \
    dom \
    iconv \
    intl \
    json \
    mbstring \
    mcrypt \
    opcache \
    pdo_mysql \
    soap \
    xml \
    xsl \
    zip \
  && docker-php-ext-configure gd \
    --with-freetype-dir=/usr/include/ \
    --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install -j$NPROC gd \
  && apk add --no-cache \
    freetype \
    gettext \
    icu \
    libjpeg-turbo \
    libmcrypt \
    libpng \
    libxslt \
  && apk del .build-deps

# Deploy Magento source code from build
ADD $MAGE_EDITION-build.tar.gz $MAGE_ROOT

# Set Magento file permissions
RUN chown -R www-data:www-data . \
  && find var vendor pub/static pub/media app/etc var -type f -exec chmod u+w {} \; \
  && find var vendor pub/static pub/media app/etc var -type d -exec chmod u+w {} \; \
  && chmod u+x bin/magento
